default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# Configuración para Heroku
production:
  adapter: postgresql
  encoding: unicode
  # Heroku usa la variable DATABASE_URL automáticamente,
  # pero Rails necesita saber que el adaptador es postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
